/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PlayerPlayerIdImport } from './routes/player.$playerId'
import { Route as LeaguestatsYearPerImport } from './routes/leaguestats.$year.$per'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PlayerPlayerIdRoute = PlayerPlayerIdImport.update({
  id: '/player/$playerId',
  path: '/player/$playerId',
  getParentRoute: () => rootRoute,
} as any)

const LeaguestatsYearPerRoute = LeaguestatsYearPerImport.update({
  id: '/leaguestats/$year/$per',
  path: '/leaguestats/$year/$per',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/player/$playerId': {
      id: '/player/$playerId'
      path: '/player/$playerId'
      fullPath: '/player/$playerId'
      preLoaderRoute: typeof PlayerPlayerIdImport
      parentRoute: typeof rootRoute
    }
    '/leaguestats/$year/$per': {
      id: '/leaguestats/$year/$per'
      path: '/leaguestats/$year/$per'
      fullPath: '/leaguestats/$year/$per'
      preLoaderRoute: typeof LeaguestatsYearPerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
  '/leaguestats/$year/$per': typeof LeaguestatsYearPerRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
  '/leaguestats/$year/$per': typeof LeaguestatsYearPerRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
  '/leaguestats/$year/$per': typeof LeaguestatsYearPerRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/player/$playerId' | '/leaguestats/$year/$per'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/player/$playerId' | '/leaguestats/$year/$per'
  id: '__root__' | '/' | '/player/$playerId' | '/leaguestats/$year/$per'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayerPlayerIdRoute: typeof PlayerPlayerIdRoute
  LeaguestatsYearPerRoute: typeof LeaguestatsYearPerRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayerPlayerIdRoute: PlayerPlayerIdRoute,
  LeaguestatsYearPerRoute: LeaguestatsYearPerRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/player/$playerId",
        "/leaguestats/$year/$per"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/player/$playerId": {
      "filePath": "player.$playerId.jsx"
    },
    "/leaguestats/$year/$per": {
      "filePath": "leaguestats.$year.$per.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
